name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install

      - name: Run Cypress Tests
        run: |
          npx cypress run

      - name: Upload Cypress videos and screenshots
        uses: actions/upload-artifact@v2
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots
